global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'class-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['class-service:3001']

  - job_name: 'course-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['course-service:3002']

  - job_name: 'student-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['student-service:3003']

  - job_name: 'teacher-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['teacher-service:3004']

  - job_name: 'schedule-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['schedule-service:3005']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

