name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev, staging ]
  pull_request:
    branches: [ main, dev, staging ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies for all services
      run: |
        cd api-gateway && npm install
        cd ../class-service && npm install
        cd ../course-service && npm install
        cd ../student-service && npm install
        cd ../teacher-service && npm install
        cd ../schedule-service && npm install
        
    - name: Build all services
      run: |
        cd api-gateway && npm run build
        cd ../class-service && npm run build
        cd ../course-service && npm run build
        cd ../student-service && npm run build
        cd ../teacher-service && npm run build
        cd ../schedule-service && npm run build

  build-docker-images:
    runs-on: ubuntu-latest
    needs: []
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: makhtarf1
        password: dckr_pat_1_7EfXLtR_EFuq7FFm8xkzQzXg4
        
    - name: Build and push API Gateway
      uses: docker/build-push-action@v4
      with:
        context: ./api-gateway
        push: ${{ github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main' }}
        tags: makhtarf1/school-api-gateway:${{ github.ref_name }}
        
    - name: Build and push Class Service
      uses: docker/build-push-action@v4
      with:
        context: ./class-service
        push: ${{ github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main' }}
        tags: makhtarf1/school-class-service:${{ github.ref_name }}
        
    - name: Build and push Course Service
      uses: docker/build-push-action@v4
      with:
        context: ./course-service
        push: ${{ github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main' }}
        tags: makhtarf1/school-course-service:${{ github.ref_name }}
        
    - name: Build and push Student Service
      uses: docker/build-push-action@v4
      with:
        context: ./student-service
        push: ${{ github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main' }}
        tags: makhtarf1/school-student-service:${{ github.ref_name }}
        
    - name: Build and push Teacher Service
      uses: docker/build-push-action@v4
      with:
        context: ./teacher-service
        push: ${{ github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main' }}
        tags: makhtarf1/school-teacher-service:${{ github.ref_name }}
        
    - name: Build and push Schedule Service
      uses: docker/build-push-action@v4
      with:
        context: ./schedule-service
        push: ${{ github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main' }}
        tags: makhtarf1/school-schedule-service:${{ github.ref_name }}
        
  deploy-dev:
    needs: build-docker-images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Render (API Gateway)
      run: |
        curl -X POST https://api.render.com/v1/services \
        -H "Authorization: Bearer rnd_8dMgGS6ExDBrJ2R7rsiVVCyyQKDf" \
        -d '{"serviceId": "school-api-gateway","env": "production","docker": { "image": "makhtarf1/school-api-gateway:dev"}}'
        
    - name: Deploy to Render (Class Service)
      run: |
        curl -X POST https://api.render.com/v1/services \
        -H "Authorization: Bearer rnd_8dMgGS6ExDBrJ2R7rsiVVCyyQKDf" \
        -d '{"serviceId": "school-class-service","env": "production","docker": { "image": "makhtarf1/school-class-service:dev"}}'
        
    - name: Deploy to Render (Course Service)
      run: |
        curl -X POST https://api.render.com/v1/services \
        -H "Authorization: Bearer rnd_8dMgGS6ExDBrJ2R7rsiVVCyyQKDf" \
        -d '{"serviceId": "school-course-service","env": "production","docker": { "image": "makhtarf1/school-course-service:dev"}}'
        
    - name: Deploy to Render (Student Service)
      run: |
        curl -X POST https://api.render.com/v1/services \
        -H "Authorization: Bearer rnd_8dMgGS6ExDBrJ2R7rsiVVCyyQKDf" \
        -d '{"serviceId": "school-student-service","env": "production","docker": { "image": "makhtarf1/school-student-service:dev"}}'
        
    - name: Deploy to Render (Teacher Service)
      run: |
        curl -X POST https://api.render.com/v1/services \
        -H "Authorization: Bearer rnd_8dMgGS6ExDBrJ2R7rsiVVCyyQKDf" \
        -d '{"serviceId": "school-teacher-service","env": "production","docker": { "image": "makhtarf1/school-teacher-service:dev"}}'
        
    - name: Deploy to Render (Schedule Service)
      run: |
        curl -X POST https://api.render.com/v1/services \
        -H "Authorization: Bearer rnd_8dMgGS6ExDBrJ2R7rsiVVCyyQKDf" \
        -d '{"serviceId": "school-schedule-service","env": "production","docker": { "image": "makhtarf1/school-schedule-service:dev"}}'
        
  deploy-prod:
    needs: build-docker-images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Render (Production)
      run: |
        curl -X POST https://api.render.com/v1/services \
        -H "Authorization: Bearer rnd_8dMgGS6ExDBrJ2R7rsiVVCyyQKDf" \
        -d '{"serviceId": "school-api-gateway","env": "production","docker": { "image": "makhtarf1/school-api-gateway:main"}}'
        
    - name: Get Deployment URLs
      run: |
        echo "API Gateway URL: https://your-render-api-gateway-url"
        echo "Class Service URL: https://your-render-class-service-url"
        echo "Course Service URL: https://your-render-course-service-url"
        echo "Student Service URL: https://your-render-student-service-url"
        echo "Teacher Service URL: https://your-render-teacher-service-url"
        echo "Schedule Service URL: https://your-render-schedule-service-url"
